# Generated by Django 2.2.6 on 2019-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20191019_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='uploaded_by',
            field=models.CharField(max_length=200),
        ),
    ]
