# Generated by Django 2.2.6 on 2019-10-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20191019_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='courses',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='uploaded_by',
            field=models.CharField(max_length=200),
        ),
    ]
