# Generated by Django 2.2.6 on 2019-10-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20191019_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_approved',
            field=models.BooleanField(default='False'),
        ),
    ]
