# Generated by Django 2.2.6 on 2019-10-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20191019_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='reg_users',
        ),
        migrations.AlterField(
            model_name='shared_notes',
            name='uploaded_by',
            field=models.CharField(max_length=200),
        ),
    ]
