# Generated by Django 2.2.6 on 2019-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20191019_1728'),
        ('Clubs', '0004_auto_20191019_1728'),
        ('Courses', '0003_auto_20191019_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('videos', models.FileField(upload_to='')),
                ('shared_notes', models.ManyToManyField(related_name='courses', to='Courses.Shared_notes')),
            ],
        ),
        migrations.CreateModel(
            name='CoursesE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
