# Generated by Django 2.2.6 on 2019-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0006_remove_clubs_courses'),
        ('Courses', '0005_auto_20191019_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesc',
            options={'verbose_name_plural': 'Courses for Clubs and Departments'},
        ),
        migrations.AlterModelOptions(
            name='coursese',
            options={'verbose_name_plural': 'External Courses'},
        ),
        migrations.AddField(
            model_name='coursesc',
            name='clubs',
            field=models.ManyToManyField(related_name='courses', to='Clubs.Clubs'),
        ),
    ]
