# Generated by Django 2.2.6 on 2019-10-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0006_remove_clubs_courses'),
        ('Courses', '0007_auto_20191020_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursese',
            name='hosted_by',
            field=models.ManyToManyField(related_name='courseE', to='Clubs.Clubs'),
        ),
    ]
