# Generated by Django 2.2.6 on 2019-10-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('CL', 'CL'), ('DE', 'DE'), ('EX', 'EX')], default='CL', max_length=2)),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.Courses')),
            ],
        ),
    ]
