# Generated by Django 2.2.6 on 2019-10-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20191019_1535'),
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('Type', models.CharField(choices=[('CL', 'CL'), ('DE', 'DE'), ('EX', 'EX')], default='CL', max_length=2)),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='Courses.Courses')),
            ],
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
