# Generated by Django 2.2.6 on 2019-10-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0003_auto_20191019_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs',
            old_name='Type',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='clubs',
            name='Courses',
        ),
    ]
